#include "ScopedMessageSubsystem.h"
#include "ScopeContextProvider.h"
#include "Engine/GameInstance.h"
#include "Engine/World.h"
#include "GameplayTagsManager.h"

DEFINE_LOG_CATEGORY(LogScopedMessageSubsystem);

UScopedMessageSubsystem& UScopedMessageSubsystem::Get(const UObject* WorldContextObject)
{
	UWorld* World = GEngine->GetWorldFromContextObject(WorldContextObject, EGetWorldErrorMode::Assert);
	UGameInstance* GameInstance = World->GetGameInstance();
	check(GameInstance);
	return *GameInstance->GetSubsystem<UScopedMessageSubsystem>();
}

bool UScopedMessageSubsystem::HasInstance(const UObject* WorldContextObject)
{
	UWorld* World = GEngine->GetWorldFromContextObject(WorldContextObject, EGetWorldErrorMode::ReturnNull);
	UGameInstance* GameInstance = World ? World->GetGameInstance() : nullptr;
	return GameInstance && GameInstance->GetSubsystem<UScopedMessageSubsystem>() != nullptr;
}

void UScopedMessageSubsystem::Deinitialize()
{
	RoutingTable.Empty();
	DynamicScopeMap.Empty();
	Super::Deinitialize();
}

// Helper function to extract a valid ScopeId from an object implementing IScopeContextProvider.
static FGameplayTag FindScopeIdOnObject(UObject* Object)
{
	if (!Object)
	{
		return FGameplayTag::EmptyTag;
	}

	// Check if the object implements the IScopeContextProvider interface.
	if (const IScopeContextProvider* Provider = Cast<IScopeContextProvider>(Object))
	{
		const FGameplayTag Tag = Provider->GetScopeId();
		if (Tag.IsValid())
		{
			return Tag;
		}
	}

	return FGameplayTag::EmptyTag;
}

FGameplayTag UScopedMessageSubsystem::GetOrCreateDynamicScopeId(const UObject* ScopeObject)
{
	if (!ScopeObject)
	{
		return FGameplayTag::EmptyTag;
	}

	UObject* NonConstScopeObject = const_cast<UObject*>(ScopeObject);
	TWeakObjectPtr<UObject> WeakKey(NonConstScopeObject);

	// Try to find the cached scope tag in our map.
	if (const FGameplayTag* FoundTag = DynamicScopeMap.Find(WeakKey))
	{
		if (FoundTag->IsValid())
		{
			return *FoundTag;
		}
	}

	// Sanitize the object name to only contain alphanumeric characters and underscores for GameplayTag compatibility.
	FString SanitizedName;
	FString OriginalName = ScopeObject->GetName();
	for (int32 i = 0; i < OriginalName.Len(); ++i)
	{
		const TCHAR Char = OriginalName[i];
		if (FChar::IsAlnum(Char) || Char == '_')
		{
			SanitizedName.AppendChar(Char);
		}
		else
		{
			SanitizedName.AppendChar('_');
		}
	}

	// Create a unique, stable tag name by appending the hash of the object's path.
	uint32 UniqueHash = GetTypeHash(ScopeObject->GetPathName());
	FString TagNameStr = FString::Printf(TEXT("Scope.AutoGenerated.%s_%08X"), *SanitizedName, UniqueHash);
	FName TagName(*TagNameStr);

	// Register the new tag dynamically in the GameplayTagsManager.
	FGameplayTag NewTag = UGameplayTagsManager::Get().AddNativeGameplayTag(TagName);
	DynamicScopeMap.Add(WeakKey, NewTag);
	return NewTag;
}

FGameplayTag UScopedMessageSubsystem::ResolveScopeId(UObject* ScopeContext) const
{
	if (!ScopeContext)
	{
		return FGameplayTag::EmptyTag;
	}

	// 1. Direct check on the provided context object.
	FGameplayTag Tag = FindScopeIdOnObject(ScopeContext);
	if (Tag.IsValid())
	{
		return Tag;
	}

	// 2. Fallback: Traverse up the outer owner chain (Level, LevelInstance, etc.).
	UObject* Current = ScopeContext;
	while (Current)
	{
		Tag = FindScopeIdOnObject(Current);
		if (Tag.IsValid())
		{
			return Tag;
		}
		Current = Current->GetOuter();
	}

	// 3. Fallback: Traverse up the physical actor attachment parent hierarchy.
	if (AActor* Actor = Cast<AActor>(ScopeContext))
	{
		AActor* Parent = Actor->GetAttachParentActor();
		while (Parent)
		{
			Tag = FindScopeIdOnObject(Parent);
			if (Tag.IsValid())
			{
				return Tag;
			}
			Parent = Parent->GetAttachParentActor();
		}
	}

	return FGameplayTag::EmptyTag;
}

void UScopedMessageSubsystem::BroadcastMessageInternal(
	FGameplayTag Channel,
	const UScriptStruct* PayloadType,
	const void* PayloadBytes,
	FGameplayTag ScopeId,
	EScopedMessageReplication Replication)
{
	if (!Channel.IsValid())
	{
		UE_LOG(LogScopedMessageSubsystem, Warning, TEXT("BroadcastMessageInternal called with invalid Channel"));
		return;
	}

	if (!PayloadType || !PayloadBytes)
	{
		UE_LOG(LogScopedMessageSubsystem, Warning, TEXT("BroadcastMessageInternal called with null PayloadType or PayloadBytes"));
		return;
	}

	FScopeChannelMap* ScopeMap = RoutingTable.Find(ScopeId);
	if (!ScopeMap)
	{
		return;
	}

	FListenerList* ListenerList = ScopeMap->ChannelMap.Find(Channel);
	if (!ListenerList)
	{
		return;
	}

	TArray<FScopedMessageListenerData> ListenersCopy = ListenerList->Listeners;
	for (FScopedMessageListenerData& Listener : ListenersCopy)
	{
		if (!Listener.Owner.IsValid())
		{
			continue;
		}

		if (Listener.PayloadType.IsValid() && Listener.PayloadType.Get() != PayloadType)
		{
			UE_LOG(LogScopedMessageSubsystem, Warning,
				TEXT("Payload type mismatch for channel %s: expected %s, got %s"),
				*Channel.ToString(),
				*GetNameSafe(Listener.PayloadType.Get()),
				*GetNameSafe(PayloadType));
			continue;
		}

		Listener.Callback(Channel, PayloadType, PayloadBytes);
	}

	if (Replication != EScopedMessageReplication::LocalOnly)
	{
		TArray<uint8> PayloadBuffer;
		FMemoryWriter Writer(PayloadBuffer);
		const_cast<UScriptStruct*>(PayloadType)->SerializeItem(Writer, const_cast<void*>(PayloadBytes), nullptr);

		NetMulticast_BroadcastMessage(Channel, ScopeId.GetTagName(), PayloadType, PayloadBuffer);
	}
}

FScopedMessageListenerHandle UScopedMessageSubsystem::SubscribeInternal(
	FGameplayTag Channel,
	TFunction<void(FGameplayTag, const UScriptStruct*, const void*)>&& Callback,
	const UScriptStruct* PayloadType,
	FGameplayTag ScopeId,
	EScopedMessageMatch MatchType,
	UObject* Owner)
{
	if (!Channel.IsValid())
	{
		UE_LOG(LogScopedMessageSubsystem, Warning, TEXT("SubscribeInternal called with invalid Channel"));
		return FScopedMessageListenerHandle();
	}

	FScopeChannelMap& ScopeMap = RoutingTable.FindOrAdd(ScopeId);
	FListenerList& ListenerList = ScopeMap.ChannelMap.FindOrAdd(Channel);

	const int32 NewHandleID = ListenerList.NextHandleID++;

	FScopedMessageListenerData& NewListener = ListenerList.Listeners.AddDefaulted_GetRef();
	NewListener.Callback = MoveTemp(Callback);
	NewListener.HandleID = NewHandleID;
	NewListener.MatchType = MatchType;
	NewListener.Owner = Owner;
	NewListener.PayloadType = PayloadType;

	return FScopedMessageListenerHandle(this, ScopeId, Channel, NewHandleID);
}

void UScopedMessageSubsystem::Unsubscribe(FScopedMessageListenerHandle& Handle)
{
	if (Handle.IsValid())
	{
		UnsubscribeInternal(Handle.ScopeId, Handle.Channel, Handle.HandleID);
		Handle = FScopedMessageListenerHandle();
	}
}

void UScopedMessageSubsystem::UnsubscribeInternal(FGameplayTag ScopeId, FGameplayTag Channel, int32 HandleID)
{
	FScopeChannelMap* ScopeMap = RoutingTable.Find(ScopeId);
	if (!ScopeMap)
	{
		return;
	}

	FListenerList* ListenerList = ScopeMap->ChannelMap.Find(Channel);
	if (!ListenerList)
	{
		return;
	}

	ListenerList->Listeners.RemoveAll([HandleID](const FScopedMessageListenerData& Listener)
	{
		return Listener.HandleID == HandleID;
	});

	if (ListenerList->Listeners.Num() == 0)
	{
		ScopeMap->ChannelMap.Remove(Channel);
		if (ScopeMap->ChannelMap.Num() == 0)
		{
			RoutingTable.Remove(ScopeId);
		}
	}
}

void UScopedMessageSubsystem::CleanupInvalidListeners(FGameplayTag ScopeId, FGameplayTag Channel)
{
	for (auto It = DynamicScopeMap.CreateIterator(); It; ++It)
	{
		if (!It.Key().IsValid())
		{
			It.RemoveCurrent();
		}
	}

	FScopeChannelMap* ScopeMap = RoutingTable.Find(ScopeId);
	if (!ScopeMap)
	{
		return;
	}

	FListenerList* ListenerList = ScopeMap->ChannelMap.Find(Channel);
	if (!ListenerList)
	{
		return;
	}

	ListenerList->Listeners.RemoveAll([](const FScopedMessageListenerData& Listener)
	{
		return !Listener.Owner.IsValid();
	});

	if (ListenerList->Listeners.Num() == 0)
	{
		ScopeMap->ChannelMap.Remove(Channel);
		if (ScopeMap->ChannelMap.Num() == 0)
		{
			RoutingTable.Remove(ScopeId);
		}
	}
}

void UScopedMessageSubsystem::NetMulticast_BroadcastMessage_Implementation(
	FGameplayTag Channel,
	FName ScopeIdName,
	const UScriptStruct* PayloadType,
	const TArray<uint8>& PayloadBytes)
{
	if (!PayloadType || PayloadBytes.Num() == 0)
	{
		return;
	}

	FGameplayTag ScopeId;
	if (!ScopeIdName.IsNone())
	{
		ScopeId = UGameplayTagsManager::Get().AddNativeGameplayTag(ScopeIdName);
	}

	FMemoryReader Reader(PayloadBytes);
	UScriptStruct* NonConstPayloadType = const_cast<UScriptStruct*>(PayloadType);
	uint8* PayloadData = static_cast<uint8*>(FMemory::Malloc(NonConstPayloadType->GetStructureSize()));
	NonConstPayloadType->InitializeStruct(PayloadData);
	NonConstPayloadType->SerializeItem(Reader, PayloadData, nullptr);

	BroadcastMessageInternal(Channel, NonConstPayloadType, PayloadData, ScopeId, EScopedMessageReplication::LocalOnly);

	NonConstPayloadType->DestroyStruct(PayloadData);
	FMemory::Free(PayloadData);
}

void UScopedMessageSubsystem::execK2_BroadcastMessage(UObject* Context, FFrame& Stack, void* const Z_Param__Result)
{
	P_GET_STRUCT(FGameplayTag, Channel);

	Stack.MostRecentPropertyAddress = nullptr;
	Stack.MostRecentPropertyContainer = nullptr;
	Stack.StepCompiledIn<FStructProperty>(nullptr);

	void* MessagePtr = Stack.MostRecentPropertyAddress;
	FStructProperty* StructProp = CastField<FStructProperty>(Stack.MostRecentProperty);

	P_GET_OBJECT(UObject, ScopeContext);
	P_GET_ENUM(EScopedMessageReplication, Replication);

	P_FINISH;

	if (!StructProp || !MessagePtr)
	{
		UE_LOG(LogScopedMessageSubsystem, Warning, TEXT("K2_BroadcastMessage: invalid message struct"));
		return;
	}

	UScopedMessageSubsystem* Subsystem = Cast<UScopedMessageSubsystem>(Context);
	if (!Subsystem)
	{
		return;
	}

	const UScriptStruct* PayloadType = StructProp->Struct;
	Subsystem->BroadcastMessageInternal(Channel, PayloadType, MessagePtr, Subsystem->ResolveScopeId(ScopeContext), Replication);
}
