#include "ScopedMessageSubsystem.h"
#include "ScopeContextProvider.h"
#include "Engine/GameInstance.h"
#include "Engine/World.h"
#include "GameplayTagsManager.h"
#include "ScopedMessageReplicatorComponent.h"
#include "GameFramework/GameStateBase.h"
#include "StructUtils/InstancedStruct.h"

DEFINE_LOG_CATEGORY(LogScopedMessageSubsystem);

UScopedMessageSubsystem& UScopedMessageSubsystem::Get(const UObject* WorldContextObject)
{
	UWorld* World = GEngine->GetWorldFromContextObject(WorldContextObject, EGetWorldErrorMode::Assert);
	UGameInstance* GameInstance = World->GetGameInstance();
	check(GameInstance);
	return *GameInstance->GetSubsystem<UScopedMessageSubsystem>();
}

bool UScopedMessageSubsystem::HasInstance(const UObject* WorldContextObject)
{
	UWorld* World = GEngine->GetWorldFromContextObject(WorldContextObject, EGetWorldErrorMode::ReturnNull);
	UGameInstance* GameInstance = World ? World->GetGameInstance() : nullptr;
	return GameInstance && GameInstance->GetSubsystem<UScopedMessageSubsystem>() != nullptr;
}

FString UScopedMessageSubsystem::GetNetModePrefix(const UObject* WorldContextObject)
{
	if (UWorld* World = GEngine->GetWorldFromContextObject(WorldContextObject, EGetWorldErrorMode::ReturnNull))
	{
		const ENetMode NetMode = World->GetNetMode();
		switch (NetMode)
		{
		case NM_Client:
			return TEXT("Client");
		case NM_DedicatedServer:
		case NM_ListenServer:
			return TEXT("Server");
		case NM_Standalone:
			return TEXT("Standalone");
		default:
			break;
		}
	}
	return TEXT("Unknown");
}

void UScopedMessageSubsystem::Initialize(FSubsystemCollectionBase& Collection)
{
	Super::Initialize(Collection);
	FWorldDelegates::OnPostWorldInitialization.AddUObject(this, &UScopedMessageSubsystem::OnWorldInitialized);
}

void UScopedMessageSubsystem::Deinitialize()
{
	RoutingTable.Empty();
	DynamicScopeMap.Empty();
	Super::Deinitialize();
}

// Helper function to extract a valid ScopeId from an object implementing IScopeContextProvider.
static FGameplayTag FindScopeIdOnObject(UObject* Object)
{
	if (!Object)
	{
		return FGameplayTag::EmptyTag;
	}

	// Check if the object implements the IScopeContextProvider interface.
	if (const IScopeContextProvider* Provider = Cast<IScopeContextProvider>(Object))
	{
		const FGameplayTag Tag = Provider->GetScopeId();
		if (Tag.IsValid())
		{
			return Tag;
		}
	}

	return FGameplayTag::EmptyTag;
}

FGameplayTag UScopedMessageSubsystem::GetOrCreateDynamicScopeId(const UObject* ScopeObject)
{
	if (!ScopeObject)
	{
		return FGameplayTag::EmptyTag;
	}

	UObject* NonConstScopeObject = const_cast<UObject*>(ScopeObject);
	TWeakObjectPtr<UObject> WeakKey(NonConstScopeObject);

	// Try to find the cached scope tag in our map.
	if (const FGameplayTag* FoundTag = DynamicScopeMap.Find(WeakKey))
	{
		if (FoundTag->IsValid())
		{
			return *FoundTag;
		}
	}

	// Sanitize the object name to only contain alphanumeric characters and underscores for GameplayTag compatibility.
	FString SanitizedName;
	FString OriginalName = ScopeObject->GetName();
	for (int32 i = 0; i < OriginalName.Len(); ++i)
	{
		const TCHAR Char = OriginalName[i];
		if (FChar::IsAlnum(Char) || Char == '_')
		{
			SanitizedName.AppendChar(Char);
		}
		else
		{
			SanitizedName.AppendChar('_');
		}
	}

	// Create a unique, stable tag name by appending the hash of the object's path.
	uint32 UniqueHash = GetTypeHash(ScopeObject->GetPathName());
	FString TagNameStr = FString::Printf(TEXT("Scope.AutoGenerated.%s_%08X"), *SanitizedName, UniqueHash);
	FName TagName(*TagNameStr);

	// Register the new tag dynamically in the GameplayTagsManager.
	FGameplayTag NewTag = UGameplayTagsManager::Get().AddNativeGameplayTag(TagName);
	DynamicScopeMap.Add(WeakKey, NewTag);
	return NewTag;
}

FGameplayTag UScopedMessageSubsystem::ResolveScopeId(UObject* ScopeContext) const
{
	if (!ScopeContext)
	{
		return FGameplayTag::EmptyTag;
	}

	// 1. Direct check on the provided context object.
	FGameplayTag Tag = FindScopeIdOnObject(ScopeContext);
	if (Tag.IsValid())
	{
		return Tag;
	}

	// 2. Fallback: Traverse up the outer owner chain (Level, LevelInstance, etc.).
	UObject* Current = ScopeContext;
	while (Current)
	{
		Tag = FindScopeIdOnObject(Current);
		if (Tag.IsValid())
		{
			return Tag;
		}
		Current = Current->GetOuter();
	}

	// 3. Fallback: Traverse up the physical actor attachment parent hierarchy.
	if (AActor* Actor = Cast<AActor>(ScopeContext))
	{
		AActor* Parent = Actor->GetAttachParentActor();
		while (Parent)
		{
			Tag = FindScopeIdOnObject(Parent);
			if (Tag.IsValid())
			{
				return Tag;
			}
			Parent = Parent->GetAttachParentActor();
		}
	}

	return FGameplayTag::EmptyTag;
}

void UScopedMessageSubsystem::BroadcastMessageInternal(
	FGameplayTag Channel,
	const UScriptStruct* PayloadType,
	const void* PayloadBytes,
	FGameplayTag ScopeId,
	EScopedMessageReplication Replication)
{
	if (!Channel.IsValid())
	{
		UE_LOG(LogScopedMessageSubsystem, Warning, TEXT("[%s] BroadcastMessageInternal called with invalid Channel"), *GetNetModePrefix(this));
		return;
	}

	if (!PayloadType || !PayloadBytes)
	{
		UE_LOG(LogScopedMessageSubsystem, Warning, TEXT("[%s] BroadcastMessageInternal called with null PayloadType or PayloadBytes"), *GetNetModePrefix(this));
		return;
	}

	UE_LOG(LogScopedMessageSubsystem, Log, TEXT("[%s] Subsystem: Broadcasting message on channel %s, Scope=%s, Replication=%d"),
		*GetNetModePrefix(this), *Channel.ToString(), *ScopeId.ToString(), (int32)Replication);

	FScopeChannelMap* ScopeMap = RoutingTable.Find(ScopeId);
	if (ScopeMap)
	{
		FListenerList* ListenerList = ScopeMap->ChannelMap.Find(Channel);
		if (ListenerList)
		{
			TArray<FScopedMessageListenerData> ListenersCopy = ListenerList->Listeners;
			for (FScopedMessageListenerData& Listener : ListenersCopy)
			{
				if (!Listener.Owner.IsValid())
				{
					continue;
				}

				if (Listener.PayloadType.IsValid() && Listener.PayloadType.Get() != PayloadType)
				{
					UE_LOG(LogScopedMessageSubsystem, Warning,
						TEXT("[%s] Payload type mismatch for channel %s: expected %s, got %s"),
						*GetNetModePrefix(this),
						*Channel.ToString(),
						*GetNameSafe(Listener.PayloadType.Get()),
						*GetNameSafe(PayloadType));
					continue;
				}

				UE_LOG(LogScopedMessageSubsystem, Log, TEXT("[%s] Subsystem: Routing message on channel %s to listener %s (Scope=%s)"),
					*GetNetModePrefix(this), *Channel.ToString(), *GetNameSafe(Listener.Owner.Get()), *ScopeId.ToString());
				Listener.Callback(Channel, PayloadType, PayloadBytes);
			}
		}
	}

	if (Replication != EScopedMessageReplication::LocalOnly)
	{
		TArray<uint8> PayloadBuffer;
		FMemoryWriter Writer(PayloadBuffer);
		const_cast<UScriptStruct*>(PayloadType)->SerializeItem(Writer, const_cast<void*>(PayloadBytes), nullptr);

		UWorld* World = GetWorld();
		if (World)
		{
			if (AGameStateBase* GameState = World->GetGameState())
			{
				if (UScopedMessageReplicatorComponent* Replicator = GameState->FindComponentByClass<UScopedMessageReplicatorComponent>())
				{
					Replicator->NetMulticast_BroadcastMessage(Channel, ScopeId.GetTagName(), PayloadType, PayloadBuffer);
				}
				else
				{
					UE_LOG(LogScopedMessageSubsystem, Warning, TEXT("BroadcastMessageInternal: Replicator component not found on GameState. Message not replicated."));
				}
			}
		}
	}
}

FScopedMessageListenerHandle UScopedMessageSubsystem::SubscribeInternal(
	FGameplayTag Channel,
	TFunction<void(FGameplayTag, const UScriptStruct*, const void*)>&& Callback,
	const UScriptStruct* PayloadType,
	FGameplayTag ScopeId,
	EScopedMessageMatch MatchType,
	UObject* Owner)
{
	if (!Channel.IsValid())
	{
		UE_LOG(LogScopedMessageSubsystem, Warning, TEXT("SubscribeInternal called with invalid Channel"));
		return FScopedMessageListenerHandle();
	}

	FScopeChannelMap& ScopeMap = RoutingTable.FindOrAdd(ScopeId);
	FListenerList& ListenerList = ScopeMap.ChannelMap.FindOrAdd(Channel);

	const int32 NewHandleID = ListenerList.NextHandleID++;

	FScopedMessageListenerData& NewListener = ListenerList.Listeners.AddDefaulted_GetRef();
	NewListener.Callback = MoveTemp(Callback);
	NewListener.HandleID = NewHandleID;
	NewListener.MatchType = MatchType;
	NewListener.Owner = Owner;
	NewListener.PayloadType = PayloadType;

	return FScopedMessageListenerHandle(this, ScopeId, Channel, NewHandleID);
}

void UScopedMessageSubsystem::Unsubscribe(FScopedMessageListenerHandle& Handle)
{
	if (Handle.IsValid())
	{
		UnsubscribeInternal(Handle.ScopeId, Handle.Channel, Handle.HandleID);
		Handle = FScopedMessageListenerHandle();
	}
}

void UScopedMessageSubsystem::UnsubscribeInternal(FGameplayTag ScopeId, FGameplayTag Channel, int32 HandleID)
{
	FScopeChannelMap* ScopeMap = RoutingTable.Find(ScopeId);
	if (!ScopeMap)
	{
		return;
	}

	FListenerList* ListenerList = ScopeMap->ChannelMap.Find(Channel);
	if (!ListenerList)
	{
		return;
	}

	ListenerList->Listeners.RemoveAll([HandleID](const FScopedMessageListenerData& Listener)
	{
		return Listener.HandleID == HandleID;
	});

	if (ListenerList->Listeners.Num() == 0)
	{
		ScopeMap->ChannelMap.Remove(Channel);
		if (ScopeMap->ChannelMap.Num() == 0)
		{
			RoutingTable.Remove(ScopeId);
		}
	}
}

void UScopedMessageSubsystem::CleanupInvalidListeners(FGameplayTag ScopeId, FGameplayTag Channel)
{
	for (auto It = DynamicScopeMap.CreateIterator(); It; ++It)
	{
		if (!It.Key().IsValid())
		{
			It.RemoveCurrent();
		}
	}

	FScopeChannelMap* ScopeMap = RoutingTable.Find(ScopeId);
	if (!ScopeMap)
	{
		return;
	}

	FListenerList* ListenerList = ScopeMap->ChannelMap.Find(Channel);
	if (!ListenerList)
	{
		return;
	}

	ListenerList->Listeners.RemoveAll([](const FScopedMessageListenerData& Listener)
	{
		return !Listener.Owner.IsValid();
	});

	if (ListenerList->Listeners.Num() == 0)
	{
		ScopeMap->ChannelMap.Remove(Channel);
		if (ScopeMap->ChannelMap.Num() == 0)
		{
			RoutingTable.Remove(ScopeId);
		}
	}
}

void UScopedMessageSubsystem::HandleReplicatedMessage(
	FGameplayTag Channel,
	FName ScopeIdName,
	const UScriptStruct* PayloadType,
	const TArray<uint8>& PayloadBytes)
{
	if (!PayloadType || PayloadBytes.Num() == 0)
	{
		return;
	}

	FGameplayTag ScopeId;
	if (!ScopeIdName.IsNone())
	{
		ScopeId = UGameplayTagsManager::Get().AddNativeGameplayTag(ScopeIdName);
	}

	UE_LOG(LogScopedMessageSubsystem, Log, TEXT("[%s] Subsystem: Received replicated message on channel %s, Scope=%s"),
		*GetNetModePrefix(this), *Channel.ToString(), *ScopeId.ToString());

	FInstancedStruct Message;
	Message.InitializeAs(PayloadType);

	FMemoryReader Reader(PayloadBytes);
	UScriptStruct* NonConstPayloadType = const_cast<UScriptStruct*>(PayloadType);
	NonConstPayloadType->SerializeItem(Reader, Message.GetMutableMemory(), nullptr);

	BroadcastMessageInternal(Channel, NonConstPayloadType, Message.GetMemory(), ScopeId, EScopedMessageReplication::LocalOnly);
}

void UScopedMessageSubsystem::K2_BroadcastMessage(
	const UObject* WorldContextObject,
	FGameplayTag Channel,
	const FInstancedStruct& Payload,
	EScopedMessageReplication Replication)
{
	if (!WorldContextObject)
	{
		UE_LOG(LogScopedMessageSubsystem, Warning, TEXT("[Unknown] K2_BroadcastMessage called with null WorldContextObject"));
		return;
	}

	if (!Payload.IsValid())
	{
		UE_LOG(LogScopedMessageSubsystem, Warning, TEXT("[%s] K2_BroadcastMessage: Payload is invalid"), *GetNetModePrefix(WorldContextObject));
		return;
	}

	if (HasInstance(WorldContextObject))
	{
		UScopedMessageSubsystem& Subsystem = Get(WorldContextObject);
		const UScriptStruct* PayloadType = Payload.GetScriptStruct();
		const void* PayloadBytes = Payload.GetMemory();
		Subsystem.BroadcastMessageInternal(Channel, PayloadType, PayloadBytes, Subsystem.ResolveScopeId(const_cast<UObject*>(WorldContextObject)), Replication);
	}
}

void UScopedMessageSubsystem::OnWorldInitialized(UWorld* World, const UWorld::InitializationValues IValues)
{
	if (World)
	{
		World->AddOnActorSpawnedHandler(FOnActorSpawned::FDelegate::CreateUObject(this, &UScopedMessageSubsystem::OnActorSpawned));

		if (AGameStateBase* GameState = World->GetGameState())
		{
			CreateReplicatorOnGameState(GameState);
		}
	}
}

void UScopedMessageSubsystem::OnActorSpawned(AActor* SpawnedActor)
{
	if (AGameStateBase* GameState = Cast<AGameStateBase>(SpawnedActor))
	{
		CreateReplicatorOnGameState(GameState);
	}
}

void UScopedMessageSubsystem::CreateReplicatorOnGameState(AGameStateBase* GameState)
{
	if (GameState && GameState->HasAuthority())
	{
		if (!GameState->FindComponentByClass<UScopedMessageReplicatorComponent>())
		{
			UScopedMessageReplicatorComponent* Comp = NewObject<UScopedMessageReplicatorComponent>(GameState, TEXT("ScopedMessageReplicator"));
			Comp->SetIsReplicated(true);
			Comp->RegisterComponent();
		}
	}
}
